name: Run Video Workflow

on:
  workflow_dispatch:
  schedule:
    # Ejecuciones programadas los jueves, sábados y domingos a la medianoche (UTC)
    - cron: '0 0 * * 4'
    - cron: '0 0 * * 6'
    - cron: '0 0 * * 0'

permissions:
  contents: write  # Otorgar permisos de escritura al repositorio para el GITHUB_TOKEN

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - name: Check out repository
        uses: actions/checkout@v2

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Instalar dependencias
      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      # Ejecutar el script principal
      - name: Run main script
        env:
          DOCS_FOLDER_ID: ${{ secrets.DOCS_FOLDER_ID }}
          VIDEOS_FOLDER_ID: ${{ secrets.VIDEOS_FOLDER_ID }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          python src/main.py

      # Configurar git para realizar commits
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Realizar commit de los cambios
      - name: Commit changes
        run: |
          git add keywords_dict.json
          git commit -m "Update keywords_dict.json [skip ci]" || echo "No changes to commit"

      # Hacer push de los cambios al repositorio
      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Subir los logs como artefacto
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: youtube_data-log
          path: youtube_data.log
