name: Run Video Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Run main script
        env:
          DOCS_FOLDER_ID: ${{ secrets.DOCS_FOLDER_ID }}
          VIDEOS_FOLDER_ID: ${{ secrets.VIDEOS_FOLDER_ID }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          python src/main.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: youtube_data-log
          path: youtube_data.log
