name: Run Video Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # todos los días a medianoche, por ejemplo

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Decode and save GCP credentials
        run: |
          echo "$GCP_CREDENTIALS" | base64 --decode > credentials.json

      - name: Run main script
        run: |
          python src/main.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: youtube_data-log
          path: youtube_data.log
